app/models.py
class Article:
    def __init__(self, source_name, author, title, description, url, image, date, content):
        self.source_name = source_name
        self.author = author 
        self.title = title
        self.description = description
        self.url = url
        self.image = image 
        self.date = date
        self.content = content


class Source:
    def __init__(self, id, name, url):
        self.id = id
        self.name = name
        self.url = url

app/__init__.py
from flask import Flask
from config import config_options


def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # Will add the views and forms
    # from .api import configure_request
    # configure_request(app)

    return app
    

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views, errors

app/main/views.py
from flask import render_template
from . import main
from ..api import get_category_headlines, get_headlines, get_source_headlines, get_sources


@main.route("/")
def home():
    overall = get_headlines("us")
    finance = get_category_headlines("us", "business")
    entertainment = get_category_headlines("us", "entertainment")
    technology = get_category_headlines("us", "technology")
    sports = get_category_headlines("us", "sports")
    sources = get_sources()
    data = [overall, finance, entertainment, sources, technology, sports]

    return render_template("index.html", data = data)


@main.route("/source/<title>")
def category(title):
    headlines = get_source_headlines(title)

    return render_template("category.html", headlines = headlines,  title = title)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="shortcut icon"
      href="../static/images/world.png"
      type="image/x-icon"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/base.css')}}"
    />
    {% block css %}{% endblock %}
    <!-- title block -->
    {% block title %}{% endblock %}
  </head>
  <body>
    <main>
      <!-- hero section -->
      <section id="grey"></section>
      <section id="hero">
        <!-- header section -->
        <header>
          <div class="logo">
            <a href="{{url_for('main.home')}}">
              <h1>News<span>Portal</span></h1>
            </a>
          </div>
          <div class="links">
            <label for="menu">
              <span>
                <svg aria-hidden="true" role="img" viewBox="0 0 24 24">
                  <path
                    fill="currentColor"
                    d="M4 6h16v2H4zm4 5h12v2H8zm5 5h7v2h-7z"
                  />
                </svg>
              </span>
              <input type="checkbox" name="menu" id="menu" />
            </label>
            <ul>
              <li><a href="{{url_for('main.home')}}">home</a></li>
              <li>
                <a href="{{url_for('main.home', _anchor='business')}}"
                  >business</a
                >
              </li>
              <li>
                <a href="{{url_for('main.home', _anchor='sports')}}">sports</a>
              </li>
              <li>
                <a href="{{url_for('main.home', _anchor='entertainment')}}"
                  >entertainment</a
                >
              </li>
              <li>
                <a href="{{url_for('main.home', _anchor='technology')}}"
                  >technology</a
                >
              </li>
            </ul>
          </div>
        </header>
        <!-- hero content -->
        <div class="hero-content">
          <div class="tag">{% block latest_title%}{% endblock %}</div>
          <div class="title">
            <div class="headline">
              {% block latest %}
              <!-- <h3>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Obcaecati voluptatem officia enim atque sit nisi expedita
                aliquid, consequatur illum omnis.
              </h3>
              <a href="">Read More . . . </a> -->
              {% endblock %}
            </div>
            <div class="calendar">
              <svg aria-hidden="true" role="img" viewBox="0 0 15 15">
                <path
                  fill="currentColor"
                  fill-rule="evenodd"
                  d="M4.5 1a.5.5 0 0 1 .5.5V2h5v-.5a.5.5 0 0 1 1 0V2h1.5A1.5 1.5 0 0 1 14 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-10A1.5 1.5 0 0 1 1 12.5v-9A1.5 1.5 0 0 1 2.5 2H4v-.5a.5.5 0 0 1 .5-.5ZM10 3v.5a.5.5 0 0 0 1 0V3h1.5a.5.5 0 0 1 .5.5V5H2V3.5a.5.5 0 0 1 .5-.5H4v.5a.5.5 0 0 0 1 0V3h5ZM2 6v6.5a.5.5 0 0 0 .5.5h10a.5.5 0 0 0 .5-.5V6H2Zm5 1.5a.5.5 0 1 1 1 0a.5.5 0 0 1-1 0ZM9.5 7a.5.5 0 1 0 0 1a.5.5 0 0 0 0-1Zm1.5.5a.5.5 0 1 1 1 0a.5.5 0 0 1-1 0Zm.5 1.5a.5.5 0 1 0 0 1a.5.5 0 0 0 0-1ZM9 9.5a.5.5 0 1 1 1 0a.5.5 0 0 1-1 0ZM7.5 9a.5.5 0 1 0 0 1a.5.5 0 0 0 0-1ZM5 9.5a.5.5 0 1 1 1 0a.5.5 0 0 1-1 0ZM3.5 9a.5.5 0 1 0 0 1a.5.5 0 0 0 0-1ZM3 11.5a.5.5 0 1 1 1 0a.5.5 0 0 1-1 0Zm2.5-.5a.5.5 0 1 0 0 1a.5.5 0 0 0 0-1Zm1.5.5a.5.5 0 1 1 1 0a.5.5 0 0 1-1 0Zm2.5-.5a.5.5 0 1 0 0 1a.5.5 0 0 0 0-1Z"
                  clip-rule="evenodd"
                />
              </svg>
              <p class="month">June</p>
              <span class="date">12</span>
            </div>
          </div>
        </div>
      </section>
      <!-- postlatest content section -->
      {% block postlatest %} {% endblock %}

      <!-- main content section -->
      {% block content %}{% endblock %}

      <!-- footer section -->
      <footer>
        <p class="footer-text">
          &copy; All Rights Reserved | <span class="year"></span>
        </p>
      </footer>
    </main>
    <script src="{{url_for('static', filename='js/base.js')}}"></script>
  </body>
</html>

app/templates/category.html
{% extends "base.html" %}

<!-- css block -->
{% block css %}
<link
  rel="stylesheet"
  href="{{url_for('static', filename='css/category.css')}}"
/>
{% endblock %}

<!-- title block -->
{% block title %}
<title>{{title}}</title>
{% endblock %}

<!-- latest title block -->
{% block latest_title%}
<h2>News from {{title}}</h2>
{% endblock %}

<!-- this is the latest block -->
{% block latest %}
<!-- content check -->
<h3>{{ headlines[0].description | truncate(150)}}</h3>
<a href="{{ headlines[0].url }}" target="blank">Read More . . . </a>
<!-- end check -->
{% endblock %}

<!-- this is the postlatest block -->
{% block postlatest %}
<section id="latest">
  <div class="first">
    <h3 class="description">{{ headlines[1].description | truncate(100)}}</h3>
    <a href=" {{ headlines[1].url }}" target="blank">Read More . . . </a>
  </div>
  <div class="second">
    <h3 class="description">{{headlines[2].description | truncate(100) }}</h3>
    <a href=" {{ headlines[2].url }}" target="blank">Read More . . . </a>
  </div>
  <div class="third">
    <h3 class="description">{{ headlines[3].description | truncate(100) }}</h3>
    <a href=" {{ headlines[3].url }}" target="blank">Read More . . . </a>
  </div>
</section>
{% endblock %}

<!-- main content block -->
{% block content %}
<!-- finance section -->
<section id="headlines">
  <div class="title">
    <h3>Top Headlines</h3>
    <hr />
  </div>

  <div class="articles">
    <!-- loop -->
    {% for piece in headlines %}
    <!-- if check -->
    {% if headlines[0] != piece and headlines[1] != piece and headlines[2] !=
    piece and headlines[3] != piece%}
    <div class="content">
      <div class="upper">
        <div class="article-image">
          <img src="{{ piece.image }}" alt="{{ piece.title}}" />
        </div>
        <div class="article-content">
          <a href="{{ piece.url }}" target="blank">
            {{ piece.description | truncate(100)}}</a
          >
        </div>
      </div>
      <div class="lower">
        <hr />
        <p>{{ piece.date }}</p>
      </div>
    </div>
    {% endif %}
    <!-- end if check -->
    {% endfor %}
  </div>
</section>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

<!-- css linking block -->
{% block css %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/index.css')}}"
/>
{% endblock %}
<!-- title block -->
{% block title%}
<title>NewsPortal</title>
{% endblock %}

<!-- latest title block -->
{% block latest_title%}
<h2>latest</h2>
{% endblock %}

<!-- this is the latest block -->
{% block latest %}
<h3>{{ data[0][0].description | truncate(150)}}</h3>
<a href="{{ data[0][0].url }}" target="blank">Read More . . . </a>
{% endblock %}

<!-- this is the postlatest block -->
{% block postlatest %}
<section id="latest">
  <div class="first">
    <h3 class="description">{{ data[0][1].description | truncate(100)}}</h3>
    <a href=" {{ data[0][1].url }}" target="blank">Read More . . . </a>
  </div>
  <div class="second">
    <h3 class="description">{{ data[0][2].description | truncate(100) }}</h3>
    <a href=" {{ data[0][2].url }}" target="blank">Read More . . . </a>
  </div>
  <div class="third">
    <h3 class="description">{{ data[0][3].description | truncate(100) }}</h3>
    <a href=" {{ data[0][3].url }}" target="blank">Read More . . . </a>
  </div>
</section>
{% endblock %}

<!-- block content section -->
{% block content %}
<!-- top headlines section -->
<section id="top-headlines">
  <div class="title">
    <h3>Top headlines</h3>
    <hr />
  </div>
  <div class="banner">
    <div class="dummy">
      <h3>{{ data[0][4].description | truncate(50) }}</h3>
      <br />
      <a href=" {{ data[0][4].url }}" target="blank">Read Now</a>
    </div>
    <div
      class="top"
      style="background-image: linear-gradient(
        to bottom,
        rgba(0, 0, 0, 0.5),
        rgba(0, 0, 0, 0.5)
      ),
      url({{data[0][4].image}})"
    >
      <p>{{ data[0][4].content | truncate(350) }}</p>
      <div class="details">
        <div class="name">
          <svg aria-hidden="true" role="img" viewBox="0 0 24 24">
            <path
              fill="currentColor"
              d="M7.5 6.5C7.5 8.981 9.519 11 12 11s4.5-2.019 4.5-4.5S14.481 2 12 2S7.5 4.019 7.5 6.5zM20 21h1v-1c0-3.859-3.141-7-7-7h-4c-3.86 0-7 3.141-7 7v1h17z"
            />
          </svg>
          <span>{{ data[0][4].author }}</span>
        </div>
        <div class="date">Published on: {{ data[0][4].date }}</div>
      </div>
    </div>
  </div>
  <div class="articles">
    {% for i in range(5, 11) %}
    <div class="content">
      <div class="upper">
        <div class="article-image">
          <img src="{{ data[0][i].image }}" alt="{{ data[0][i].title}}" />
        </div>
        <div class="article-content">
          <a href="{{ data[0][i].url }}" target="blank">
            {{ data[0][i].description | truncate(100)}}</a
          >
        </div>
      </div>
      <div class="lower">
        <hr />
        <p class="date">{{ data[0][i].date }}</p>
      </div>
    </div>
    {% endfor %}
  </div>
</section>

<!-- sources section -->
<section id="sources">
  <div class="title">
    <h3>Our trusted news outlets</h3>
    <hr />
  </div>
  <div class="outlets">
    {% for i in range(0, 16) %}
    <a href="{{url_for('main.category', title = data[3][i].id )}}">
      <div class="outlet">{{ data[3][i].name }}</div>
    </a>
    {% endfor %}
  </div>
</section>

<!-- finance section -->
<section id="business">
  <div class="title">
    <h3>business</h3>
    <hr />
  </div>
  <div class="banner">
    <div class="dummy">
      <h3>{{ data[1][0].description | truncate(50) }}</h3>
      <br />
      <a href=" {{ data[1][0].url }}" target="blank">Read Now</a>
    </div>
    <div
      class="top"
      style="background-image: linear-gradient(
        to bottom,
        rgba(0, 0, 0, 0.5),
        rgba(0, 0, 0, 0.5)
      ),
      url({{data[1][0].image}})"
    >
      <p>{{ data[1][0].content | truncate(350) }}</p>
      <div class="details">
        <div class="name">
          <svg aria-hidden="true" role="img" viewBox="0 0 24 24">
            <path
              fill="currentColor"
              d="M7.5 6.5C7.5 8.981 9.519 11 12 11s4.5-2.019 4.5-4.5S14.481 2 12 2S7.5 4.019 7.5 6.5zM20 21h1v-1c0-3.859-3.141-7-7-7h-4c-3.86 0-7 3.141-7 7v1h17z"
            />
          </svg>
          <span>{{ data[1][0].author }}</span>
        </div>
        <div class="date">Published on: {{ data[1][0].date }}</div>
      </div>
    </div>
  </div>
  <div class="articles">
    {% for i in range(1, 7) %}
    <div class="content">
      <div class="upper">
        <div class="article-image">
          <img src="{{ data[1][i].image }}" alt="{{ data[1][i].title}}" />
        </div>
        <div class="article-content">
          <a href="{{ data[1][i].url }}" target="blank">
            {{ data[1][i].description | truncate(100)}}</a
          >
        </div>
      </div>
      <div class="lower">
        <hr />
        <p>{{ data[1][i].date }}</p>
      </div>
    </div>
    {% endfor %}
  </div>
</section>

<!-- entertainment section -->
<section id="entertainment">
  <div class="title">
    <h3>entertainment</h3>
    <hr />
  </div>
  <div class="banner">
    <div class="dummy">
      <h3>{{ data[2][0].description | truncate(50) }}</h3>
      <br />
      <a href=" {{ data[2][0].url }}" target="blank">Read Now</a>
    </div>
    <div
      class="top"
      style="background-image: linear-gradient(
        to bottom,
        rgba(0, 0, 0, 0.5),
        rgba(0, 0, 0, 0.5)
      ),
      url({{data[2][0].image}})"
    >
      <p>{{ data[2][0].content | truncate(350) }}</p>
      <div class="details">
        <div class="name">
          <svg aria-hidden="true" role="img" viewBox="0 0 24 24">
            <path
              fill="currentColor"
              d="M7.5 6.5C7.5 8.981 9.519 11 12 11s4.5-2.019 4.5-4.5S14.481 2 12 2S7.5 4.019 7.5 6.5zM20 21h1v-1c0-3.859-3.141-7-7-7h-4c-3.86 0-7 3.141-7 7v1h17z"
            />
          </svg>
          <span>{{ data[2][0].author }}</span>
        </div>
        <div class="date">Published on: {{ data[2][0].date }}</div>
      </div>
    </div>
  </div>
  <div class="articles">
    {% for i in range(1, 7) %}
    <div class="content">
      <div class="upper">
        <div class="article-image">
          <img src="{{ data[2][i].image }}" alt="{{ data[2][i].title}}" />
        </div>
        <div class="article-content">
          <a href="{{ data[2][i].url }}" target="blank">
            {{ data[2][i].description | truncate(100)}}</a
          >
        </div>
      </div>
      <div class="lower">
        <hr />
        <p>{{ data[2][i].date }}</p>
      </div>
    </div>
    {% endfor %}
  </div>
</section>

<!-- technology section -->
<section id="technology">
  <div class="title">
    <h3>Technology</h3>
    <hr />
  </div>
  <div class="banner">
    <div class="dummy">
      <h3>{{ data[4][0].description | truncate(50) }}</h3>
      <br />
      <a href=" {{ data[4][0].url }}" target="blank">Read Now</a>
    </div>
    <div
      class="top"
      style="background-image: linear-gradient(
        to bottom,
        rgba(0, 0, 0, 0.5),
        rgba(0, 0, 0, 0.5)
      ),
      url({{data[4][0].image}})"
    >
      <p>{{ data[4][0].content | truncate(350) }}</p>
      <div class="details">
        <div class="name">
          <svg aria-hidden="true" role="img" viewBox="0 0 24 24">
            <path
              fill="currentColor"
              d="M7.5 6.5C7.5 8.981 9.519 11 12 11s4.5-2.019 4.5-4.5S14.481 2 12 2S7.5 4.019 7.5 6.5zM20 21h1v-1c0-3.859-3.141-7-7-7h-4c-3.86 0-7 3.141-7 7v1h17z"
            />
          </svg>
          <span>{{ data[4][0].author }}</span>
        </div>
        <div class="date">Published on: {{ data[4][0].date }}</div>
      </div>
    </div>
  </div>
  <div class="articles">
    {% for i in range(1, 7) %}
    <div class="content">
      <div class="upper">
        <div class="article-image">
          <img src="{{ data[4][i].image }}" alt="{{ data[2][i].title}}" />
        </div>
        <div class="article-content">
          <a href="{{ data[4][i].url }}" target="blank">
            {{ data[4][i].description | truncate(100)}}</a
          >
        </div>
      </div>
      <div class="lower">
        <hr />
        <p>{{ data[4][i].date }}</p>
      </div>
    </div>
    {% endfor %}
  </div>
</section>

<!-- sports section -->
<section id="sports">
  <div class="title">
    <h3>Sports</h3>
    <hr />
  </div>
  <div class="banner">
    <div class="dummy">
      <h3>{{ data[5][0].description | truncate(50) }}</h3>
      <br />
      <a href=" {{ data[5][0].url }}" target="blank">Read Now</a>
    </div>
    <div
      class="top"
      style="background-image: linear-gradient(
        to bottom,
        rgba(0, 0, 0, 0.5),
        rgba(0, 0, 0, 0.5)
      ),
      url({{data[5][0].image}})"
    >
      <p>{{ data[5][0].content | truncate(350) }}</p>
      <div class="details">
        <div class="name">
          <svg aria-hidden="true" role="img" viewBox="0 0 24 24">
            <path
              fill="currentColor"
              d="M7.5 6.5C7.5 8.981 9.519 11 12 11s4.5-2.019 4.5-4.5S14.481 2 12 2S7.5 4.019 7.5 6.5zM20 21h1v-1c0-3.859-3.141-7-7-7h-4c-3.86 0-7 3.141-7 7v1h17z"
            />
          </svg>
          <span>{{ data[5][0].author }}</span>
        </div>
        <div class="date">Published on: {{ data[5][0].date }}</div>
      </div>
    </div>
  </div>
  <div class="articles">
    {% for i in range(1, 7) %}
    <div class="content">
      <div class="upper">
        <div class="article-image">
          <img src="{{ data[5][i].image }}" alt="{{ data[5][i].title}}" />
        </div>
        <div class="article-content">
          <a href="{{ data[5][i].url }}" target="blank">
            {{ data[5][i].description | truncate(100)}}</a
          >
        </div>
      </div>
      <div class="lower">
        <hr />
        <p class="date">{{ data[5][i].date }}</p>
      </div>
    </div>
    {% endfor %}
  </div>
</section>
{% endblock %}

app/templates/not-found.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="shortcut icon"
      href="../static/images/world.png"
      type="image/x-icon"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/error.css')}}"
    />
    <title>404</title>
  </head>
  <body>
    <main>
      <h1>404</h1>
      <h2>The page you are looking for doesn't exist!</h2>
      <a href="{{url_for('main.home')}}">Return Home</a>
    </main>
  </body>
</html>